modLoader="javafml"
loaderVersion="[47,)"
license="MIT"

[[mods]]
modId="amdium"
version="${file.jarVersion}"
displayName="Amdium - AMD Optimizer"
authors="Amdium Team"
logoFile="assets/amdium/icon.png"
description='''
Amdium - AMD GPU/APU Optimizer for Minecraft.
Optimizes performance for AMD Radeon graphics and Ryzen CPUs.
Supports APU (integrated graphics) and discrete Radeon cards.
'''

[[dependencies.amdium]]
modId="forge"
mandatory=true
versionRange="[47,)"
ordering="NONE"
side="CLIENT"

[[dependencies.amdium]]
modId="minecraft"
mandatory=true
versionRange="[1.20.1,)"
ordering="NONE"
side="CLIENT"
